config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html  
  root "index#index"

  get "notes", to: "notes#index", as: :notes

  # get "products", to: "products#index"
  # get "products/listing", to: "products#listing"
  # get "products/:id", to: "products#show"
  get "products/api", to: "products#api", as: :products_api
  get "products/generate", to: "products#generate_products", as: :generate_products
  # get "products/page(/:page)", to: "products#index", as: :products_page
  resources :products
  get "product-categories/api", to: "product_categories#api"
  get "product-categories/generate-product-categories", to: "product_categories#generate_categories", as: :generate_product_categories
  resources :product_categories, path: 'product-categories'
  # get "/signup", to: "auth_users#new"
  # post "/signup", to: "auth_users#create"

  #
  # Auth Users Routes
  #
  # resources :auth_users, path: "/auth/users"
  # get "/auth/users", to: "auth_uses#index"
  # get "/auth/users/[:id]", to: "auth_users#show"
  # get "/auth/users/new", to: "auth_users#new"  
  # post "/auth/users", to: "auth_users#create"

  get 'auth/users', to: 'auth_users#index'
  get 'auth/users/generate', to: 'auth_users#generate_users', as: :generate_users
  get 'auth/users/new', to: 'auth_users#new', as: :new_user
  post 'auth/users', to: 'auth_users#create'
  get 'auth/users/:id', to: 'auth_users#show', as: :auth_user
  get 'auth/users/:id/edit', to: 'auth_users#edit', as: :edit_auth_user
  patch 'auth/users/:id', to: 'auth_users#update'
  delete 'auth/users/:id', to: 'auth_users#destroy'

end

app/models/auth_user.rb
class AuthUser < ApplicationRecord
	has_one :auth_user_detail
	accepts_nested_attributes_for :auth_user_detail, reject_if: :all_blank
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true, length: { minimum: 10 }
  # scope :auth_user_detail, lambda {|auth_user|
  # 	joins(:auth_user_detail).
  # 	where( auth_user_detail: {user_id: auth_user})
  # }

end

app/controllers/auth_users_controller.rb
#auth_users
class AuthUsersController < ApplicationController

  def initialize
    super
    @page = "users"
  end

  def index
    @auth_users = AuthUser.all()
  end

  def show
    @auth_user = AuthUser.find(params[:id])
    @auth_user_details =  @auth_user.auth_user_detail()
    # return render plain: @auth_user.inspect
  end

  def new
    @auth_user = AuthUser.new
    #
    # [NOTE]
    # - If you ommit AuthUserDetail.new, user detail fields do not appear of first request.
    #   But they do appear after form submission.
    #   Find out why this happens.
    #

    # The following are the same. Probably 'build' prefix works as an alias (?).
    # @auth_user.build_auth_user_detail
    @auth_user.auth_user_detail = AuthUserDetail.new
  end

  def create

    #
    # Passing this hardcoded object instead of user_params populates both tables
    #
    params = {
      email: "delasthanos@gmail.com",
      password_digest: "delasthanos@gmail.com",
      auth_user_detail_attributes: {
        firstname: "thanos",
        lastname: "delas"
      }
    }

    @auth_user = AuthUser.new(user_params)
    @auth_user.auth_user_detail = AuthUserDetail.new(user_params[:auth_user_detail_attributes])

    if @auth_user.save
      flash[:success] = "User created successfully"
      redirect_to action: "index"
    else      
      render 'new'
    end

  end

  def edit
    @auth_user = AuthUser.find(params[:id])
    @auth_user_details =  @auth_user.auth_user_detail()
    # return render plain: @auth_user.inspect
    # @auth_user_details = @auth_user.auth_user_detail()
    # return render plain: @auth_user_details.inspect
    # @auth_user.build_auth_user_detail(:firstname => "go", :lastname => "go2")
    # @auth_user.auth_user_detail.find(params[:id])
    # return render plain: @auth_user.inspect
  end

  def update
    @auth_user = AuthUser.find(params[:id])    

    if @auth_user.update(user_params)
      flash[:success] = "User updated successfully"
      redirect_to @auth_user
    else
      render :edit
    end

  end

  def destroy
    @auth_user = AuthUser.find(params[:id])
    @auth_user.auth_user_detail.destroy
    @auth_user.destroy

    flash[:danger] = "User with email "+@auth_user.email+" deleted successfully"
    redirect_to auth_users_path
  end

  def generate_users
    users = AuthUser.all()

    if users.length > 0
      users.each do |user|
        # user.auth_user_detail.destroy
      end
      users.destroy_all()
    end

    usersToImport = [
      {
        email: "delasthanos@gmail.com",
        password_digest: "passwordhash",
        auth_user_detail_attributes: {
          firstname: "thanos",
          lastname: "delas"
        }
      },
      {
        email: "gregsmith@example.com",
        password_digest: "passwordhash",
        auth_user_detail_attributes: {
          firstname: "gregsmith",
          lastname: "Smith"
        }
      },
      {
        email: "nikilauad@example.com",
        password_digest: "passwordhash",
        auth_user_detail_attributes: {
          firstname: "Niki",
          lastname: "Lauda"
        }
      },
    ]

    usersToImport.each do |user|
      user = AuthUser.new(user)
      result = user.save()
      if !result
        return render plain: result.inspect
      end
    end

    14.times { |i| 

      user_email = "user#{i}@example.com"
      user_passowrd = (0...50).map { ('a'..'z').to_a[rand(26)] }.join

      user = AuthUser.new(
        "email": user_email,
        "password_digest": user_passowrd
      )

      user.auth_user_detail = AuthUserDetail.new({firstname: "firstname", lastname: "lastname"})

      if !user.save()
        flash[:danger] = "Could not generate users: "+user.errors.messages.inspect+user.errors.full_messages.inspect
        return redirect_to action: "index"
      end
    }

    flash[:success] = "Users created successfully"

    return redirect_to action: "index"

  end

  private def user_params

    # params.require(:auth_user).permit(:email, :password_digest)
    # return params.require(:auth_user).permit!
    params.require(:auth_user).permit(
      :email,
      :password_digest,
      auth_user_detail_attributes: [:id, :firstname, :lastname]
    )
  end

end

app/views/auth_users/edit.html.erb
<h2>Edit User</h2>

<div class="row">

  <div class="col-md-6">
    <%= form_with(model: @auth_user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'mb-1 form-control' %>

      <%= f.label :password_digest %>
      <%= f.text_field :password_digest, class: 'mb-1 form-control' %>

      <hr />

      <%= f.fields_for :auth_user_detail do |details| %>
        <div class="user-details-form">
          <h6>User details</h6>
          <hr />
          <div>
            <%= details.label :firstname %>
            <%= details.text_field :firstname, class: 'mb-1 form-control' %>
          </div>
          <div >
            <%= details.label :lastname %>
            <%= details.text_field :lastname, class: 'mb-1 form-control' %>
          </div>
        </div>
      <% end %>

      <a href="<%= auth_user_path%>" class="mt-3 btn btn-sm btn-danger">Cancel</a>
      <%= f.submit "Update User", class: "mt-3 btn btn-sm btn-success" %>
    <% end %>
  </div>
  
</div>

app/views/auth_users/index.html.erb
<h2>Users</h2>

<a href="<%= new_user_path%>" class="btn btn-sm btn-success my-2">Create User</a>
<a href="<%= generate_users_path%>" class="btn btn-sm btn-warning my-2">Generate Dummy Users</a>

<div class="listing">
  <ul>
    <% @auth_users.each do |auth_user| %>
      <li>
        <%= auth_user.email%>
        <%= link_to "Delete", auth_user_path(auth_user), class: "crud-action", method: :delete, data: { confirm: 'Are you sure?' } %>
        <a href="<%= edit_auth_user_path(auth_user) %>" class="crud-action">Edit</a>
        <a href="<%= auth_user_path(auth_user) %>" class="crud-action">View</a>
      </li>
    <% end %>
  </ul>
</div>

app/views/auth_users/new.html.erb
<h2>Create User</h2>

<div class="row">

  <div class="col-md-6">
    <%= form_with(model: @auth_user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'mb-1 form-control' %>

      <%= f.label :password_digest %>
      <%= f.text_field :password_digest, class: 'mb-1 form-control' %>

      <hr />

      <!-- Find out why the following two work -->
      <%#= f.fields_for :auth_user_detail, AuthUserDetail.new do |details| %>
      <!-- Initialization of user details moved inside controller new -->
      <%= f.fields_for :auth_user_detail do |details| %>
      <%#= f.fields_for :auth_user_detail_attributes do |details| %>      
        <div class="user-details-form">
          <h6>User details</h6>
          <hr />
          <div>
            <%= details.label :firstname %>
            <%= details.text_field :firstname, class: 'mb-1 form-control' %>
          </div>
          <div >
            <%= details.label :lastname %>
            <%= details.text_field :lastname, class: 'mb-1 form-control' %>
          </div>
        </div>
      <% end %>

      <a href="<%= auth_users_path%>" class="mt-3 btn btn-sm btn-danger">Cancel</a>
      <%= f.submit "Create User", class: "mt-3 btn btn-sm btn-primary" %>
    <% end %>
  </div>
  
</div>

app/views/auth_users/show.html.erb
#views/users/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <a href="<%= auth_users_path%>" class="btn btn-sm btn-primary mt-2">All Users</a>
    <div>
      <h2><%= @auth_user.email %></h2>
    </div>
    <hr />
    <h6>Details</h6>
    <div>
      <b>email:</b> <%= @auth_user.email %>
    </div>
    <div>
      <b>firstname:</b> <%= @auth_user_details.firstname %>
    </div>
    <div>
      <b>lastname:</b> <%= @auth_user_details.firstname %>
    </div>
    <hr />
    <div>
      <pre><%= @auth_user.inspect %></pre>
      <pre><%= @auth_user_details.inspect %></pre>
    </div>
    <hr />
    <div>
      <%= link_to "Delete", auth_user_path(@auth_user), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to "Edit", edit_auth_user_path(@auth_user), class: "btn btn-sm btn-warning" %>
    </div>
  </div>
</div>