config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html  
  root "index#index"

  get "notes", to: "notes#index", as: :notes

  # get "products", to: "products#index"
  # get "products/listing", to: "products#listing"
  # get "products/:id", to: "products#show"
  get "products/api", to: "products#api", as: :products_api
  get "products/generate", to: "products#generate_products", as: :generate_products
  # get "products/page(/:page)", to: "products#index", as: :products_page
  resources :products
  get "product-categories/api", to: "product_categories#api"
  get "product-categories/generate-product-categories", to: "product_categories#generate_categories", as: :generate_product_categories
  resources :product_categories, path: 'product-categories'
  # get "/signup", to: "auth_users#new"
  # post "/signup", to: "auth_users#create"

  #
  # Auth Users Routes
  #
  # resources :auth_users, path: "/auth/users"
  # get "/auth/users", to: "auth_uses#index"
  # get "/auth/users/[:id]", to: "auth_users#show"
  # get "/auth/users/new", to: "auth_users#new"  
  # post "/auth/users", to: "auth_users#create"

  get 'auth/users', to: 'auth_users#index'
  get 'auth/users/generate', to: 'auth_users#generate_users', as: :generate_users
  get 'auth/users/new', to: 'auth_users#new', as: :new_user
  post 'auth/users', to: 'auth_users#create'
  get 'auth/users/:id', to: 'auth_users#show', as: :auth_user
  get 'auth/users/:id/edit', to: 'auth_users#edit', as: :edit_auth_user
  patch 'auth/users/:id', to: 'auth_users#update'
  delete 'auth/users/:id', to: 'auth_users#destroy'

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	# If you use dependent: :destroy child deletes parent category
	belongs_to :parent_category, class_name: 'ProductCategory', foreign_key: 'parent_id', optional: true
	# You can delete all children with parent using has_many
	has_many :parent_categories, class_name: 'ProductCategory', foreign_key: 'parent_id', dependent: :destroy
	validates :name, presence: true, length: { minimum: 5 }

	NULL_ATTRS = %w( parent_id )

	before_save :blank_parent_category

  def self.children_ids(parent_id)

    query = "
      SELECT id, name, parent_id
      FROM (SELECT * FROM product_categories
      	ORDER BY parent_id, id)
      product_categories,
      (SELECT @pv := ? ) initialisation
      WHERE find_in_set(parent_id, @pv) > 0
      AND @pv := CONCAT(@pv, ',', id)
    "

    # children = ActiveRecord::Base.connection.exec_query(query, 100)
    children = ActiveRecord::Base.connection.exec_query(
    	ActiveRecord::Base.send(:sanitize_sql_array, [query, parent_id])
    )

    collect_ids = []

    collect_ids.push(parent_id)

  	children.each do |category|
  		collect_ids.push(category["id"])
  	end

    return collect_ids
  end

	protected

		def blank_parent_category
			NULL_ATTRS.each { |attr| self[attr] = nil if self[attr].blank? || self[attr]==0 }
		end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController

  include ProductCategoriesHelper  

  def initialize
    super
    @page = "product_categories"
    @product_categories_to_html = []
  end

  def index
    @title = "Product Categories"
    @product_categories = ProductCategory.all()
    @product_categories_parse = []

    @product_categories_nested = parse_categories(@product_categories)

    #
    # Return json if application/json exists in headers
    #
    if(request.headers["Content-Type"].to_s.include? "json" || true)
      response.headers['Content-Type'] = 'application/json'
      return self.json(@product_categories_nested)
    end

    # return render plain: @product_categories_to_html.inspect
    # return parse_categories(@product_categories)
  end

  #
  # Dispatch parse categories
  #
  def parse_categories(categories)

    # Conert active record categories to json
    categories = @product_categories.as_json

    # parse_poduct_categories_presentation(categories, nil)
    return parse_poduct_categories(categories)
    # return render plain: parse_poduct_categories(categories)
    # return render json: @product_categories_parse.to_json

    # o = []
    # o.append("Parse categories <br />")
    # o.append(categories)
    # o.append(@product_categories_to_html)
    # o.append(@product_categories_parse)
    # o.append(@product_categories_parse.inspect)
    # return render inline: o.join("<br />")
  end

  #
  # Parse categories hierachy for presentation
  #
  def parse_poduct_categories_presentation(categories, selected_id=nil, depth=-1, parent_id=nil)

    depth += 1
    symbol = "--"
    categories.each do |c|
      if parent_id == c["parent_id"]
        html = []
        html.append(symbol*depth)
        html.append(c["name"])
        @product_categories_to_html.append(html.join(""))
        parse_poduct_categories_presentation(categories, selected_id, depth, c["id"])
      end
    end

  end

  #
  # Parse categories hierachy
  #
  def parse_poduct_categories(categories, result = [], depth=-1, parent_id=nil)

    depth += 1
    categories.each do |c|
      if parent_id == c["parent_id"]

        c["children"] = []
        result.append(c)
        parse_poduct_categories(categories, c["children"], depth, c["id"])
      end
    end

    return result

  end

  def api
    @product_categories = ProductCategory.all()
    return self.json(parse_categories(@product_categories))
  end

  def show
    @product_category = ProductCategory.find(params[:id])
    # return render plain: params[:id].inspect
  end

  def new
    @product_category = ProductCategory.new
    @product_categories = ProductCategory.all()
  end

  def create

    @product_category = ProductCategory.new(product_category_params)

    if @product_category.save
      flash[:success] = "Product category created"
      redirect_to @product_category
    else
      # Required if errors found
      @product_categories = ProductCategory.all()
      render :new
      #render :json => { :errors => @article.errors.full_messages }
    end
  end

  #
  # Find an elegant (preferably) way to select existing category
  #
  def edit
    @product_category = ProductCategory.find(params[:id])
    @product_categories = ProductCategory.all()
  end

  def update

    @product_category = ProductCategory.find(params[:id])

    if @product_category.update(product_category_params)
      redirect_to @product_category
    else
      # Required if errors found
      @product_categories = ProductCategory.all()
      render :edit
    end

  end

  def destroy
    @product_category = ProductCategory.find(params[:id])
    @product_category.destroy

    redirect_to product_categories_path
  end

  def generate_categories

    product_categories = ProductCategory.all()
    product_categories.destroy_all()

    require 'json'
    product_categories_file = File.read('./db/dummy-content/product-categories.json')

    begin
      product_categories = JSON.parse(product_categories_file)
    rescue StandardError => e
      flash[:danger] = "Something went wrong while trying to parse json file: ./db/dummy-content/product-categories.json <br /> #{e.to_s}"
      return redirect_to action: "index"
    end

    product_categories["product_categories"].each do |product_category|
      category = ProductCategory.new(
        "id": product_category["product_category_id"], 
        "name": product_category["name"],
        "parent_id": product_category["parent_product_category_id"],
      )
      if !category.save()
        flash[:danger] = "Could not generate product category: "+category.errors.messages.inspect+category.errors.full_messages.inspect
        redirect_to action: "index"
      end
    end

    flash[:message] = "Product categories generated successfully"
    return redirect_to action: "index"
  end

  private
    def product_category_params
      params.require(:product_category).permit(:name, :parent_id)
    end

end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper

	#
	# Print nested categories
	#
  def print_categories(categories)

  	@collect_html = '<ul class="nested-categories">'
  	categories = categories.as_json
		parse_poduct_categories_presentation(categories)
		@collect_html += "</ul>"

		return @collect_html.html_safe
  end

	#
	# Print nested categories options
	# To be wrapped in select tag
	# Use for create / update product categories
	#
  def print_categories_dropdown_options(categories, category)

  	@selected_category = category;
  	@collect_html = ''
  	categories = categories.as_json
		parse_categories_dropdown(categories)
		# You can set empty parent category to "null" or ""
		@collect_html = '<option value="null">-</option>'+@collect_html;
		return @collect_html.html_safe
  end

	#
	# Print nested categories options
	# To be wrapped in select tag
	# Use for create / update product	
	#
  def print_product_categories_dropdown_options(categories, selected_category_id)
  	@collect_html = ''
    @selected_product_category_id = selected_category_id
  	parse_categories_dropdown_for_product(categories)  	
  	return @collect_html.html_safe
  end

  private

	  #
	  # Parse categories hierachy for presentation
	  #
	  def parse_poduct_categories_presentation(categories, depth=-1, parent_id=nil)

	    depth += 1
	    nested_width = 12;
	    symbol = " * "
	    categories.each do |c|
	      if parent_id == c["parent_id"]
	        html = []

	        html.append('<li style="padding-left: '+(nested_width*(depth+1)).to_s+'px">')
		        html.append('<a href="'+product_category_path(c["id"])+'">')
			        html.append(symbol*depth)
			        html.append(c["name"]+"("+c["id"].to_s+")")
	        	html.append('</a>')
	        html.append('</li>')

	        @collect_html += html.join("")
	        # collect_html += c["name"]

	        parse_poduct_categories_presentation(categories, depth, c["id"])
	      end
	    end

	  end

	  #
	  # Parse categories hierachy for dropdown select
	  #
	  def parse_categories_dropdown(categories, depth=-1, parent_id=nil)

	    depth += 1
	    nested_width = 12;
	    symbol = "-"
	    categories.each do |c|
	      if parent_id == c["parent_id"]
	        html = []

	        selected = ''
	        selected = 'selected' if c["id"] == @selected_category['parent_id']

	        html.append('<option style="padding-left: '+(nested_width*(depth+1)).to_s+'px" value="'+c["id"].to_s+'" '+selected+'>')
		        html.append(symbol*depth)
		        html.append(c["name"])
	        html.append('</option>')
	        @collect_html += html.join("")

	        parse_categories_dropdown(categories, depth, c["id"])
	      end
	    end

	  end

	  #
	  # Parse categories hierachy for products dropdown select
	  #
	  def parse_categories_dropdown_for_product(categories, depth=-1, parent_id=nil)

	    depth += 1
	    nested_width = 12;
	    symbol = "-"
	    categories.each do |c|
	      if parent_id == c["parent_id"]
	        html = []

	        selected = ''
	        selected = 'selected' if c["id"] == @selected_product_category_id

	        html.append('<option style="padding-left: '+(nested_width*(depth+1)).to_s+'px" value="'+c["id"].to_s+'" '+selected+'>')
		        html.append(symbol*depth)
		        html.append(c["name"])
	        html.append('</option>')
	        @collect_html += html.join("")

	        parse_categories_dropdown_for_product(categories, depth, c["id"])
	      end
	    end

	  end

end

app/views/product_categories/_form.html.erb
<%= form_with(model: @product_category, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
    <% product_category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>

    <% product_category.errors.details.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <% if @product_category.errors.any? %>
    <div id="error_explanation">
      <div>
        <%= pluralize(@product_category.errors.count, "error") %> prohibited
        this article from being saved:
      </div>
      <ul>
        <% @product_category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# Use the following to generate a dropdown %>
  <% if false %>
  <div class="form-group">
    <label>Parent Category</label>
    <%= form.collection_select(:parent_id, ProductCategory.all, :id, :name, {:include_blank => "-"}, {class: "form-control"}) %>
  </div>
  <% end %>

  <%# Hradcoded parent id for testing %>
  <!-- <div><input type="text" name="product_category[parent_id]" value="203"></div> -->

  <%#= print_categories_dropdown_options(@product_categories, @product_category) %>

  <% if true %>
  <div class="form-group">
    <label>Parent Category</label>
    <select class="form-control" name="product_category[parent_id]">
      <%= print_categories_dropdown_options(@product_categories, @product_category) %>
    </select>
  </div>
  <% end %>

  <div>
    <a href="<%= product_categories_path%>" class="btn btn-sm btn-danger">Cancel</a>
    <button class="btn btn-sm btn-success">Save</button>
  </div>
<% end %>

app/views/product_categories/edit.html.erb
<div class="row">
	<div class="col-md-6 col-sm-12">
		<h2>Edit Product Category</h2>
		<%= render "form", product_category: @product_category %>
	</div>
</div>

app/views/product_categories/index.html.erb
<h2><%= @title%></h2>

<a href="<%= generate_product_categories_path%>" class="btn btn-sm btn-warning my-2">Generate Product Categories</a>
<a href="<%= product_categories_api_path%>" class="btn btn-sm btn-info my-2">Product Categories Api</a>
<a href="<%= new_product_category_path%>" class="btn btn-sm btn-success my-2">Create Product Category</a>

<div class="listing">

  <ul>
    <% @product_categories_to_html.each do |category| %>
      <li><%= category %></li>
    <% end %>
  </ul>

  <div class="my-3">
    <% if false %>
      <pre><%= @product_categories_nested.inspect %></pre>
    <% end %>

    <%= print_categories(@product_categories) %>
  </div>

  <%# Flat Categories %>
  <% if false %>
  <ul>
    <% @product_categories.each do |product_category| %>
    <li>
      <div>
        <%#= link_to product_category.name, product_category %>
        <div class="product_category-title-link">
          <a href="<%= product_categories_path+"/#{product_category.id}" %>"><%= product_category.name%></a>          
        </div>        
        <div>
          <%= link_to "Delete", product_category_path(product_category), class: "crud-action", method: :delete, data: { confirm: 'Are you sure?' } %>
          <a href="<%= edit_product_category_path(product_category) %>" class="crud-action">Edit</a>
          <a href="<%= product_category_path(product_category) %>" class="crud-action">View</a>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/product_categories/new.html.erb
<div class="row">
	<div class="col-md-6 col-sm-12">
		<h2>New Product Category</h2>
		<%= render "form", product_category: @product_category %>
	</div>
</div>

app/views/product_categories/show.html.erb
<a href="<%= product_categories_path%>" class="btn btn-sm btn-primary mt-2">All Product Categories</a>

<div class="row">
	<div class="col-sm-12">
		<div>
			<h2><%= @product_category.name%></h2>
		</div>
		<hr />
		<div>
			<%= link_to "Delete", product_category_path(@product_category), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
			<%= link_to "Edit", edit_product_category_path(@product_category), class: "btn btn-sm btn-warning" %>			
		</div>
	</div>
</div>