config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html  
  root "index#index"

  get "notes", to: "notes#index", as: :notes

  # get "products", to: "products#index"
  # get "products/listing", to: "products#listing"
  # get "products/:id", to: "products#show"
  get "products/api", to: "products#api", as: :products_api
  get "products/generate", to: "products#generate_products", as: :generate_products
  # get "products/page(/:page)", to: "products#index", as: :products_page
  resources :products
  get "product-categories/api", to: "product_categories#api"
  get "product-categories/generate-product-categories", to: "product_categories#generate_categories", as: :generate_product_categories
  resources :product_categories, path: 'product-categories'
  # get "/signup", to: "auth_users#new"
  # post "/signup", to: "auth_users#create"

  #
  # Auth Users Routes
  #
  # resources :auth_users, path: "/auth/users"
  # get "/auth/users", to: "auth_uses#index"
  # get "/auth/users/[:id]", to: "auth_users#show"
  # get "/auth/users/new", to: "auth_users#new"  
  # post "/auth/users", to: "auth_users#create"

  get 'auth/users', to: 'auth_users#index'
  get 'auth/users/generate', to: 'auth_users#generate_users', as: :generate_users
  get 'auth/users/new', to: 'auth_users#new', as: :new_user
  post 'auth/users', to: 'auth_users#create'
  get 'auth/users/:id', to: 'auth_users#show', as: :auth_user
  get 'auth/users/:id/edit', to: 'auth_users#edit', as: :edit_auth_user
  patch 'auth/users/:id', to: 'auth_users#update'
  delete 'auth/users/:id', to: 'auth_users#destroy'

end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, presence: true, length: { minimum: 5 }, uniqueness: true
  validates :description, presence: true, length: { minimum: 10 }
  belongs_to :product_category, class_name: 'ProductCategory', foreign_key: 'product_category_id', required: true

  NULL_ATTRS = %w( product_category_id )

  before_save :blank_product_category_id

  def self.products

    if @pagination[:page] > 1
      @pagination[:offset] = (@pagination[:page] - 1) * @pagination[:per_page]
    end    

    @products = select('products.*, product_categories.name as category_name')
      .order(created_at: :asc)
      .limit(@pagination[:per_page])
      .offset(@pagination[:offset])
      .joins(:product_category)
    
    #
    # You should find a more elegant way to calculate total results with filters
    # see: https://stackoverflow.com/questions/14227761/how-to-select-data-for-defined-page-and-total-count-of-records
    # @pagination[:total] = @products.except(:offset, :limit).count
    #
    total = Product.select("*").joins(:product_category)

    if @filters.key?("product_name")
      total = total.where("products.name like ?", "%"+@filters["product_name"]+"%")
      @products = @products.where("products.name like ?", "%"+@filters["product_name"]+"%")
    end

    if @filters.key?("product_category_id") && @filters["product_category_id"] != '-'
      @products = @products.where(product_category_id: ProductCategory.children_ids(@filters[:product_category_id]))
      total = total.where(product_category_id: ProductCategory.children_ids(@filters[:product_category_id]))
    end

    @pagination[:total] = total.count
    @pagination[:pages] = (total.count / @pagination[:per_page].to_f).ceil

    @pagination[:showing] = (@pagination[:offset]+1).to_s+" - "+(@pagination[:offset]+@pagination[:per_page]).to_s
    if total.count < @pagination[:per_page]
      @pagination[:showing] = total.count
    end

    return @products
  end

  def self.filters(filters)

    @filters = filters
    return @filters

  end

  def self.pagination(page)

    @pagination = {
      page: page,
      per_page: 10,
      total: 0,
      pages: 0,
      offset: 0,
      showing: ""
    }

    return @pagination

  end

  protected

    def blank_product_category_id
      NULL_ATTRS.each { |attr| self[attr] = nil if self[attr].blank? || self[attr]==0 }
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def initialize
    super
    @page = "products"
  end

  def index

    @title = "Products Listing"

    # children_ids = ProductCategory.children_ids
    # return render plain: children_ids.inspect

    # Check if page exists in params or set to 1
    page = 1
    if params.has_key?(:page)
      page = params[:page].to_i
    end
    
    Product.filters(request.params)
    @pagination = Product.pagination(page)
    @products = Product.products
    @product_categories = ProductCategory.all()

    #
    # Return json if application/json exists in headers
    #
    if(request.headers["Content-Type"].to_s.include? "json" || true)
      response.headers['Content-Type'] = 'application/json'
      return self.json({
        "data": @products,
        "pagination": @pagination
      })
    end

  end

  def api
    @products = Product.all()
    # return render json: @products
    return self.json(@products)
  end

  def show
    @product = Product.find(params[:id])
    # return render plain: params[:id].inspect
  end

  def new
    @product = Product.new
    @product_categories = ProductCategory.all()
  end

  def create

    @product = Product.new(product_params)
    @product_categories = ProductCategory.all()

    if @product.save
      flash[:success] = "Product created"
      redirect_to @product
    else      
      render :new
      #render :json => { :errors => @article.errors.full_messages }
    end
  end

  def edit
    @product = Product.find(params[:id])
    @product_categories = ProductCategory.all()
  end

  def update

    @product = Product.find(params[:id])
    @product_categories = ProductCategory.all()

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end

  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  def generate_products
    products = Product.all()
    products.destroy_all()

    #
    # Insert products from json
    #
    require 'json'
    products_file = File.read('./db/dummy-content/products.json')

    begin
      products = JSON.parse(products_file)
    rescue StandardError => e
      flash[:danger] = "Something went wrong while trying to parse json file: ./db/dummy-content/products.json <br /> #{e.to_s}"
      return redirect_to action: "index"
    end

    products["products"].each do |product_data|
      product = Product.new(
        "name": product_data["name"],
        "description": product_data["description"],
        "product_category_id": product_data["category_id"],
      )
      if !product.save()
        # return render plain: product.inspect
        flash[:danger] = "Could not generate product: "+
          +product["name"]+" "+
          +product.errors.messages.inspect+
          +product.errors.full_messages.inspect
        return redirect_to action: "index"
      end
    end

    #
    # Insert random products
    #
    20.times { |i| 

      product_name = "Product - #{i+1} "+(0...10).map { ('a'..'z').to_a[rand(26)] }.join
      product_description = "Description #{i} "+(0...100).map { ('a'..'z').to_a[rand(26)] }.join

      product = Product.new(
        "name": product_name,
        "description": product_description,
        "product_category_id": 100
      )

      if !product.save()
        flash[:danger] = "Could not generate products: "+
          +product.errors.messages.inspect+
          +product.errors.full_messages.inspect
        return redirect_to action: "index"
      end
    }

    return redirect_to action: "index"

  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :product_category_id)
    end

end

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>

  <%= product.errors.inspect %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
    <% product.errors.full_messages_for(:name).each do |message| %>
      <div class="error"><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "form-control" %>
    <% product.errors.full_messages_for(:description).each do |message| %>
      <div class="error"><%= message %></div>
    <% end %>
  </div>

  <%# <input type="text" name="product[product_category_id]" value="100" /> %>

  <div class="form-group">
    <label>Select Product Category</label>
    <select class="form-control" name="product[product_category_id]">
      <option>-</option>
      <%= print_product_categories_dropdown_options(@product_categories, @product['product_category_id']) %>
    </select>
    <% product.errors.full_messages_for(:product_category).each do |message| %>
      <div class="error"><%= message %></div>
    <% end %>
  </div>

  <div>
    <a href="<%= products_path%>" class="btn btn-sm btn-danger">Cancel</a>
    <button class="btn btn-sm btn-success">Save</button>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="row">
	<div class="col-md-6 col-sm-12">
		<h2>Edit Product</h2>
		<%= render "form", product: @product %>
	</div>
</div>

app/views/products/index.html.erb
<h2><%= @title%></h2>

<a href="<%= generate_products_path%>" class="btn btn-sm btn-warning my-2">Generate Dummy Products</a>
<a href="<%= products_api_path%>" class="btn btn-sm btn-info my-2">Products Api</a>
<a href="<%= new_product_path%>" class="btn btn-sm btn-success my-2">Create Product</a>

<div class="listing">

  <%= "No products found" if @pagination[:total] == 0 %>  

  <% if @pagination[:total] > 0 %>

    <div>
      <%= "Showing "+@pagination[:showing].to_s+" results, from "+@pagination[:total].to_s+" total" if @pagination[:total] > 0 %>
    </div>

    <% if false %>
    <div>
      <% if @pagination[:page] > 1%>
        <a href="<%= products_page_path%>/<%= @pagination[:page]-1%>">Previous</a>
      <% end %>
      Page <%= @pagination[:page]%> of <%= @pagination[:pages]%> 

      <% if @pagination[:page] < @pagination[:pages]%>
        <a href="<%= products_page_path%>/<%= @pagination[:page]+1%>">Next</a>
      <% end %>
    </div>
    <% end %>

    <div id="pagination">
      <% if @pagination[:page] > 1%>
        <button class="btn btn-sm" data-page="<%= @pagination[:page]-1%>">Previous</button>
      <% end %>

      Page <%= @pagination[:page]%> of <%= @pagination[:pages]%> 

      <% if @pagination[:page] < @pagination[:pages]%>
        <button class="btn btn-sm" data-page="<%= @pagination[:page]+1%>">Next</button>
      <% end %>
    </div>


  <% end %>

  <hr />

  <form id="prodcuts-search-form" class="search-form">

    <input type="hidden" name="page" value="<%= @pagination[:page] %>">

    <div class="form-group">
      <label>Search</label>
      <input class="form-control" type="text" name="product_name" value="<%= request.params[:product_name]%>" placeholder="">
    </div>

    <div class="form-group">
      <label>Select Product Category</label>
      <select class="form-control" name="product_category_id">
        <option>-</option>
        <%= print_product_categories_dropdown_options(@product_categories, request.params[:product_category_id].to_i) %>
      </select>
    </div>

    <button type="submit" class="btn btn-sm btn-success">Search</button>

  </form>

  <hr />

  <ul>
    <% @products.each do |product| %>
    <li>
      <!--<pre><%= product.inspect%></pre>-->
      <div>
        <%#= link_to product.name, product %>
        <div class="product-title-link">
          <a href="<%= products_path+"/#{product.id}" %>"><%= product.name%></a>
        </div>

        In category: <%= product.category_name %>

        <%# WARNING: Investigate further to find out where selects happen%>
        <!-- In category: <%= product.product_category.name %> -->

        <div>
          <%= link_to "Delete", product_path(product), class: "crud-action", method: :delete, data: { confirm: 'Are you sure?' } %>
          <a href="<%= edit_product_path(product) %>" class="crud-action">Edit</a>
          <a href="<%= product_path(product) %>" class="crud-action">View</a>          
        </div>

      </div>
    </li>
    <% end %>
  </ul>
</div>

<%= javascript_pack_tag 'products' %>

app/views/products/new.html.erb
<div class="row">
	<div class="col-md-6 col-sm-12">
		<h2>New Product</h2>
		<%= render "form", product: @product %>
	</div>
</div>

app/views/products/show.html.erb
<a href="<%= products_path%>" class="btn btn-sm btn-primary mt-2">All Products</a>

<div class="row">
	<div class="col-sm-12">
		<div>
			<h2><%= @product.name%></h2>
		</div>
		<hr />
		<h6>Product Description</h6>
		<div>
			<%= @product.description %>
		</div>
		<hr />
		<div>
			<%= link_to "Delete", product_path(@product), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
			<%= link_to "Edit", edit_product_path(@product), class: "btn btn-sm btn-warning" %>			
		</div>
	</div>
</div>